language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: ZbcO2lK4Iq+VW3xlssLmQeF77FAnOLj9dZW7HXZ9yu0YLlAlvkScO3CR9ZdIg5f2WSlL+BYuk1Ebgsk0qyHYfsIJbFZsstwqmuenQ59bZkhI5oOR4fEL22a8gIvYNoVvrkC0cZfUu8Hh6eY66KAHvFqCfKcRriitouahPzcm7wVoKvYGGTMWdOLQJTK9JfI/nzIZ8dSbiTbLHxRvIdHuBRImL6qKBA0mgbPnQaRkcdrc0zQepHrpVOldyI6TTV3RLNkhJNLkp5uPEff3jeVUcByN6yBh2TIGJYu41ao8ebVeaAeyw5ywyzL8SQMHNkDR5is3So1ZQcKtjPxYScYgFo+1aF6tg5lJXdD5e7HIrgPVAfx/0lxD26I4I8S/k65UfSCcdoCvFq/RErsIv9k2AQ59k2bQG3vE4nxlzkAAS/R8VoJ1nD770hV7xMeVQNVPnIXGddZstHadiFQsfsnZ3pan4WQG6UYpt0sjcnPwCZ0D2ggggblisAobskwdkienTstiFCiPdxWZT+HqOsKXmn9nDmqM80L6eHha8yyzps2e5W0UAKOMPuGCWu9dkp/LFglKkFwEAVZxgnvcs/ToJRz0z6T0pHU6XBMOCC1zs9G5yi125AKwMBj/coykz5RYKU4XKWSE7Kt4LhyExFwPezBJTh+8nxrJongt3oQl4IA=
  app: mercedesbernard
  skip_cleanup: true
  on:
    repo: mercedesb/personal-site