language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Iit7QK4bGjpJFId1joyqMzngmzvP4GX+rE/RToXeP0Phb/1u0vao6hwujEfbtf541tBh2LeHSedkXJbXbpgKijsD/U5uR1NDs15t5DiNc0+4JzLiSiIyXJ8ZgbAjQALkxJwDR8P8te7CYinPUFHAPmLpyLV4mjRHAboAq0vukPo1NWW+qkrSVUdyvOxLO6287yV7qEm7tXRUuP1Q2QLRfALncQjPTA5XhhJLmnXCa+r3X7KzUdWIDP42b/kT2SfDxRuBa6kd6naI+89cv8qusy4SFqplFedCiDXR9O/enuHglcgQ94EP47cqxM/cK/kvRJQ0yUhpJ+aIp69WIFXWxaB9aXqzIeRUog1perRHVoScfTr2litbTCWopUOkDoZ2/PzlH6jK18EtLX+5W8hbYf0Xk+UJ3CIkYw7N7zpEHbruAK0ROVKcHiqNOajUuuD6+inpl2VxPWBbz/FhEQRGKvnnl3aGCoQDuY6c9fzADnmm0LI1EVzF0h3uQh6CmOs/KluntHz3yl8mv5+V1BuYe15Dpa/H4DbVN6RPutJDaOMPqnjoM9oX6oQDSP60ccvtLBWMUlQiCSkD9BjKHK8YRpTx217JJOSNxqIzTfiwVGXi2u7v25YVIGJvJKKlRJR4gJMH5TBgJW/kWtvvy4UjQoiZH32Od2lIzWrd3PqEk4A=
  app: mercedesbernard
  on:
    repo: mercedesb/personal-site
