language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Si2BjlhB872QQoMo/c8qh0sBjSmFLvW74FFQfecMMgFmb2gJQAP6M5CrV2dBhobGvtJ7M/CnzpGbHeXQrh1vLMTuqA80rlxlvbWnZBzFY4f6Ezcsu8Tbmqd1GBYr9zbmt82QQ3noApGPaDcw2TDXOGplDX19/jM01RbPiOnT39l0+zk4bZL6TRlfyUlXkL68NZNqPGGOnY9+YO9BZTq8iJrXyKOiKWxRfxLNhDcXbfIGRKmb0FAqhqqx7eFf3ynRSxlRuwNF5brBgnFNASLfmzOWPBuWq+9x2huAcITJNE2ah/EJqdtfcz+D0Nbwh2f2zQkdu86/QaYqxXeF9NCZE0uH4pEXNEaFJH7heKiK8Rz0RvMdttiDXIHPJRwycaCZIJ9ptYeeivT+waqKFfvOjRd6qtT/e1hjgOzCjuKak4lKUBVb7aauxXPG34pG40nbb+4A9HNN1C+b/OBO9+pAwoJfAvxABZMgwSGGEOFWlDNGJarLySFR02i1UzNyWDRuUg6SHr3Sbiuu5HKrIMvSCdNpXrJAFVOdKfGH4WMleQv9XjHUg3BXr96/woiV1P1VI8yZFH/iOeL9HRvKItsqiZ558Ppf4REQv2gTM5tl7G8TbSSiIDpxBY4feBMk1fSkXcpP4LsIyLhKPDi6LKUOyMd2ynzbYm0oigOQgyNOwC8=
  app: mercedesbernard
  skip_cleanup: true
  on:
    repo: mercedesb/personal-site
