language: node_js
node_js:
- "10.11.0"
before_install:
  - npm i -g npm@6.4.1
script:
- npm test
before_deploy:
- npm run build
deploy:	
  provider: heroku	
  app: $HEROKU_APP_NAME	
  api_key: $HEROKU_AUTH_TOKEN	
  skip_cleanup: true 