language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: i5hsM2c9mkwjvT7+X6w8NJqMZfk3b8EqWtIXq0c7dg44bkQHkivHjEzOxFofCP0y9bERZ+La8Yv1sbEXG77vYohUZYOy0RfbCyiRMRCpBmX5X3VF3e6SFrp4jbmIYfb/HrKI7yUTGcLEjb6kP3FL+OQCMV/vqrzY+1pH8mXAC6AT5WjNVd1qmC+lMBl5oFMK+3T7D7mbs5i3WwA4QpM5Q9LKThRBmI371+HpOlMZlJSB/mkU45C+iZnFp9VUtmmWKF9SOaMJYNFS2+mYPDhS3nbBDmpRE2FVr94ACRBiL8WPAkb0ZtB55czYTaXMXWUzoHj9lOWcl3ngVqBftdhfbyIzSxSVRqNVfhtWh7xCMeay4adR5L0PuQ2pz6NvdQj2BMXzhaHpHFq1GEHfKg4jy8Clm7hSKg2R2kFo21JcXvV6n7WC6JvC7FJlLB6n+mVdg1Ok+IfIMD805FHYorurTIoQW/XOGohpv/WEYQsuTCQN0mXmRVBE9Z7ZzgZeu5/PDpqIA2oF/YDiXp/ZESm/HpJDxaF+XmSHxyfYdLfhQm2QcIoN44Qm0o3QOk0XsPRfhp9Lf554T7TLjHdP50VR5KZ5ysXLAR7mRPrB4HuTPBixNhHb+AO9mAGWmG2vPhwl40SA7SiCQGGMVZ/jnTe7OY+jRr7VpyDSQWIgF306DAU=
  app: mercedesbernard
  on:
    repo: mercedesb/personal-site
