language: node_js
node_js:
- stable
script:
  - npm test
  - npm run build
after_success:
  - .travis/push.sh
env:
  global:
    secure: mADR8LTbJafSBupGj5KaSJJhFy8IXMV+L9Ajtw2sEtolydayUEX4xPN+DH1nfc/SUiIpgdZAbLgFvTk7Iwbp/A76pynjYtZmRQOLcx1A2hPGyvGxBtAczli20yBhtbk0qvJCv7bulr6cx1Dh5Px9yJinwA5raXOUuwujDCRPTbe1vJlJwwixPAwOHKJpMkgt1LFVlv1KVxboMONxEI8DoG3C27/yiZin41SXRug+w+ffx5k189bMEgrtMvGd4kS5WgMKNOCm5HtQHa/e+gAuXr9kY+Qp0gZljT0GiRTI4I22+N0wFneYa9nofqJ94I8BFIYJSXxyA4kZJGdRlT7s4FN1ST+UDFaO+QGlgB/73Xg6UJr2W3GJjCzmym8G5qje9JLyxLKQUVhKAq+KOTjN8ZT6wwoeQ5C7owWgqziwSxnN45qAgirK9FBZgRz0rK2VTuaMprEqHXX27a7cumKZr/Jbw6SwdhYlUpsyu3kAYGL5P1NOKzdRxk3kLduWaGeTB4shdE/tu48TBMjKuVcK2zUrbXQBSP9ps/E0khFPdG7eLNNxszmeeURJallz3/zgBQR4ydISQPJtO11ef8hzfzWUOufZ28N28ow/ehKxP1cVuGrD23skofP98BoEoQYp0RdvWKtNvVwxgP9HdBqTX0RzM/SC1v2+c65q9r/cJZI=
