language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: SHDsGcWgtLC+KCubhVSHkkUiLQkzpwdjngDgsSHZ5ovD4+ACkfwA8DA2nkA/+Cb6ZBUFOhT2r+SmPEodBXb8+IIc6knZ2BXwmqu5+cVA3Zy8DIsFK9VidBwBFDus30mGDEBvivdoTrgRggXpCQBY6pYQnQ+A18uKTE7kSQPabscLpoPea0eyTAFzTC4FndiDla//SFHlYQ8F1fVYmeVxIRUFslnulJUBNFdZ12jxKfc+YlLduUWErzg3l4ZR9jOcKxA1gij9fajBfMnAtvz4xlAZIsZed315uYFMbtcHBUz060YVZPaSW8F3RBM7ng3rOoPwNgrcAgjo6l2wyZaW8qocsiO1F+c45tT8x2RhH+sLCciun5qoG5wBnogoY1lASeFkmhk0RHKiB3mgKMaR08svn26A+Q2j97PVMmglqNlzRVOZQX79M/gEW7C0ezusrf7JI4z4MyLeyJgzK3a3eF6z4uJeNf9KrZJ9askyguuwktiwA/heUmHtLsNln+jogO45mnRUkRHi+pdauazbhOr5e07w+EfrWRq8qIBmwyfRkDYWyAQN3R3whQNQ9nv49rm4oW5T+TxL/ZDQuf5/qjrM78cTStKJcnPNGg+ZVO6DDNQHj+Zuz3jRKfLz4UqfOPIiietIcXEAvQ1Plz5fXpHIjzZU6rUJay2pV8GfQR4=
  app: mercedesbernard
  skip_cleanup: true
  on:
    repo: mercedesb/personal-site
