language: node_js
node_js:
- stable
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: s0jKapjbPBaHyveLCHlM6Wbxb0SEFtkAn1hj2o11rGA/Nd/rqApsVqHrBEdsu8cKx7H3gjq0ORYauinAFvWuNGvqWk3cVCZ+DvdpHpdtfDXDcxQUX02FYH4N9ItkA1OglaBoTlwNcX7wqs2kblCn/HYu81aWN6Qu5Mx7BwXWjFtUeHwsVvVVBbMZyZMwaJ3YFwuKvn5+ZvJPU8kFYKPBlrt/aS4UaEJLJL4hgav/NesOMWJXUAP/gmSSNAzZ8GYhq0SidTMwipDvomdrkzRTdN/yRKx484Btcm7gQIrhwqvA9x/jtJ+rBXA8HAJGFKZDwFE6zRKDstEfXiZPHHGMnVthDihyy5qP4OBk1IZ/xvOzHk082Go/C6vK9ijWE9AS0q9FFieIXDWLfF19J9e3fy5ZJB5NlBXJxqDT5veAX93XeIZN8Tr3ieWF1I6BeCB6nPv7ZBEJzaxJDe7bCUc6gOVegIuBFPIcGVSAOvMzfMAMMFqfauuNGXqsIUd8PvA0edCxm7xrMMlCkZSYcMgAeqRx2YLmfbY+hiqK4EvxPw/Foeo2bOF48imWHhJbUofbKq+5xWrWVFMGpSkEt8ozQ6KxnOxY9RkcbIyXLxSVYDQopfPOeVhFD7C96QxCUKaH8EKG78+bqVpLxLFdRWJIsQ632aNB7b0yzxyc235KKig=
  app: mercedesbernard
  skip_cleanup: true
  on:
    repo: mercedesb/personal-site
