language: node_js
node_js:
- stable
before_deploy:
- npm run build
# deploy:
#   provider: heroku
#   api_key:
#     secure: iA2nCsuwwpFn9t/ZsDMCM3xHcXV/UdisF+LbPOM+SnGWTHCMWw8WIpTfTtdbsgCtwSwftovqwxIOnb5oa0qh7ynTWuFnkwUSV7dzqSaSB0mXc15E5hJ1UhIPJyb8nqcsZipo9UKHvKMvvE12h9qSsvxiL9VzA3D5otxyBXoKObU3uXDSbQnuJVwjFH5Mdl/wSZj4YHWqZq4Qo2wTMZR5ogAeQHl986vNps0uCUJdSFODKLNWZivRWYKBaqZw56TqNsirQ5dwESq5Dmlm16m4iZq8aKq+RKIePTj8ge+LTqH1jdmxzHLNiBMchjW9sv+fjJFoztbCqnhuCHLihMo2nq0kLHDAc816b8VJNDYM1yWN2XjC+zTjW4c0aYQyuuvyI4nDyNjTOJRe8ObQPqthJMwukMaDAvVv0WKf8AD3MialiiBg/SoHMzZx5hTA0SerHNkEsLOmgvwjT1lCK0vtcQGVbpBMZ/kmtqgeNtH2l1YmfH2Fm2HTjyDJveFZwZmM9GBoNGO0W/Vs2Xwvn8B8zj+pQAQdVEuhQPmkLVzBPbPjYCHE/INc0Lgj1IIRia3zngu+ZyfQXnYCuGjj4xHKTGs3CZx7BAMJnOKDGc/nS9Pgj11Zt+z0o2plm8DmH4pz40gdANs+ORejlzVwxI6yQ2qUvdAB55OrBbEBhiAZBEg=
#   app: mercedesbernard
#   on:
#     repo: mercedesb/personal-site
